### ISSUE TITLE
cant start server

### ISSUE THREAD

**Issue by tyoc213** [koaning/pytest-duration-insights#3]
Hi there just tried to get a report on python 3.6.9 on Linux (installed with pip install) and I got this
```
pytest-duration-insights explore reportlog.json 
usage: server.py [-h] [--cgi] [--bind ADDRESS] [port]
server.py: error: unrecognized arguments: --directory /tmp/tmpf0hoc4c1/static

```

**Comment by koaning** [comment]
Ah! Yeah you'll need python 3.7 and up. The directory flag wasn't added before then.

**Comment by koaning** [comment]
I realise that while the unit tests on github reflect this, the setup.py file doesn't. 

Making a PR right away https://github.com/koaning/pytest-duration-insights/pull/4
